AWAY, HOME = range(2)
STRIKEOUT, WALK, WILD_PITCH, HIT_BY_PITCH, CONTACT, BUNT, CAUGHT_STEALING, STOLE_BASE, PASSED_BALL, DEF_INDIFFERENCE, BR_OUT_ADVANCING, BR_PICKED_OFF, REACH_ON_INTERFERENCE, BALK, FOUL_BALL_ERROR, UNKNOWN_ERROR = range(16)
LINE_DRIVE, LINE_OUT, GROUND_BALL, POP_FLY, FLY_BALL, UNKNOWN_CONTACT_TYPE = range(6)

POSITIONS = ['P', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF']
